name: 기능 개발 PR
description: 새로운 기능 개발이나 개선 작업을 위한 Pull Request 템플릿입니다.
title: "[Feature] "  # PR 제목에 자동으로 붙는 접두사
labels: ["feature", "backend"]

body:
  - type: textarea
    id: summary
    attributes:
      label: 🔍 개요
      placeholder: 이 PR이 무엇을 해결하거나 구현하는지 간단히 작성해주세요.
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: ✨ 주요 변경사항
      placeholder: |
        - 회원 가입 로직 수정
        - Cart 엔티티에 필드 추가
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ 작업 체크리스트
      options:
        - label: 코드가 정상적으로 동작함
        - label: 테스트가 통과함
        - label: 문서가 최신 상태로 유지됨
        - label: 리뷰어가 이해할 수 있도록 설명이 충분함

  - type: textarea
    id: test
    attributes:
      label: 🧪 테스트 방법
      placeholder: |
        - Postman으로 회원가입 요청 → 200 OK
        - JUnit 테스트 16개 통과
    validations:
      required: false

  - type: input
    id: issue
    attributes:
      label: 📎 관련 이슈
      placeholder: Closes #123, Fixes #456
    validations:
      required: false

  - type: textarea
    id: concerns
    attributes:
      label: 🤔 고민해볼 점
      placeholder: |
        - 도메인 간 의존성 구조 괜찮을지?
        - 예외 처리 위치가 애매한데 조언 부탁드립니다.
    validations:
      required: false

  - type: textarea
    id: review
    attributes:
      label: 🙏 리뷰 요청사항
      placeholder: |
        - 서비스 로직 구조 리뷰 부탁드립니다.
        - 테스트 방식 괜찮은지 확인해주세요.
    validations:
      required: false
